### ISSUE TITLE
Conflicting use of 'view' in Solang as compared to Remix IDE

### ISSUE THREAD

**Issue by JeremyConnor** [hyperledger-labs/solang#319]
This is my code AssetTransfer.sol, with a little modification. I have added two new events which I am using in the ```viewBalance``` and ```findOwner``` functions. When I deploy the contract on Remix IDE, I am prompted to remove the ```view``` from these function types as I am not just viewing the data but also emitting it. But, when I go on to create WASM and ABI file in Solang, it doesn't work and it hints me to add view to the functions. These both are conflicting. I think this might be the reason I am not able to deploy my modified contract on Polkadot UI.
```
pragma solidity ^0.6.0;

contract AssetTransfer {
    
    /*
    *    SendTo is a structure which will store the basic information for every receiver.
    *    SendTo.sender is the person sending the Asset.
    *    SendTo.hexOfAsset is the hash of the Asset being sent.
    *    SendTo.paid will initially be false, and will be updated to true when the reciver has paid for the asset.
    */
    struct SendTo{
        address sender;
        string hexOfAsset;
        bool paid;
    }
    
    //    registered is a map of every Registered user.
    mapping(address => uint) registered;
    
    /*
    *    balance is a map of every registered user.
    *    By default, the balance would be 1000.
    */
    mapping(address => uint) balance;
    
    //    assetToOwner maps hash of every Asset to it's current owner.
    mapping(string => address) assetToOwner;
    
    /*   send maps the receiver's address to the SendTo structure.
    *    where SendTo is the information for every corresponding receiver.
    */
    mapping(address => SendTo) send;
    
    event successfulRegistration(address _newUser);
    event assetSent(address sender, address receiver, string hexOfAsset);
    event addedAsset(address sender, string _hexAsset);
    event viewingBalance(address sender, uint balance);
    event foundOwner(address owner, string _hashOfAsset);
    event assetReceived(address owner, string _hashOfAsset);
    
    /*    
    *    onlyRegistered is a modifier which checks that the person who 
    *    has called a particular function must be a registered user.
    */
    modifier onlyRegistered() {
        require(registered[msg.sender] > 0, "You are not a registered user!");
        _;
    }
    
    //    viewBalance is used to view balance of the person who has called the function.
    function viewBalance(address _user) public returns(uint) {
        emit viewingBalance(_user, balance[_user]);
        return balance[_user];
    }
    
    /*
    *    Every user must be registered before participating in a transaction.
    *    For this purpose, a person must make a function call to registre function.
    *    Upon successful registration, the registered mapping will be updated and
    *    the user will be credited with a balance of 1000 units.
    */
    function register(address _newUser) public {
        registered[_newUser] = 1;
        balance[_newUser] = 1000;
        if(registered[_newUser] > 0){
            emit successfulRegistration(_newUser);
        }
    }
    
    /*
    *    If a person wishes to add an asset which is not owned by anyone,
    *    then the person must make a function call to addAsset function.
    *    The person shouls pass the hash of the Asset to own it.
    */
    function addAsset(string memory _hexAsset) public onlyRegistered {
        assetToOwner[_hexAsset] = msg.sender;
        emit addedAsset(msg.sender, _hexAsset);
    }
    
    // findOwner function can be used by anyone to find the owner of a specific Asset.
    function findOwner(string memory _assetHex) public returns(address addressOfOwner) {
        require(assetToOwner[_assetHex] != address(0x0), "The asset doesn't exist!");
        emit foundOwner(assetToOwner[_assetHex], _assetHex);
        return assetToOwner[_assetHex];
    }
    /*
    *    If a registered user wishes to transfer an asset to another registeres user,
    *    the he uses the sendAsset function. The sender must keep few points under consideration,
    *    1) the receiver must have paid for the previous transaction, if any and
    *    2) the sender must have the ownership of the Asset before sending it.
    *    Sending an Asset doesn't mean that the ownership of the Asset has been transferred.
    *    It will only be successful when the receiver claims it.
    */
    function sendAsset(string memory _assetHex, address _receiver) public onlyRegistered {
        require(assetToOwner[_assetHex] == msg.sender, "You are not the owner of the asset!");
        if(send[_receiver].sender != address(0x0)){
            if(send[_receiver].paid != true){
                revert();
            }
        }
        send[_receiver].sender = msg.sender;
        send[_receiver].hexOfAsset = _assetHex;
        send[_receiver].paid = false;
        emit assetSent(msg.sender, _receiver, _assetHex);
    }
    
    /*
    *    The receiver must claim the Asset by calling the receiveAsset function.
    *    The receiver must have minimum balance of 5 units to claim the Asset. 
    */
    function receiveAsset() public onlyRegistered returns(string memory) {
        require(send[msg.sender].sender != address(0x0), "You have no asset to receive!");
        require(balance[msg.sender] >= 5, "You don't have enough balance!");
        balance[msg.sender] -= 5;
        balance[send[msg.sender].sender] += 5;
        assetToOwner[send[msg.sender].hexOfAsset] = msg.sender;
        send[msg.sender].paid = true;
        emit assetReceived(msg.sender, send[msg.sender].hexOfAsset);
        return send[msg.sender].hexOfAsset;
    }
    
}
```

**Comment by JeremyConnor** [comment]
Update : I am able to deploy this contract. I had to decrease the value of endowments from 1000 (previous value) to 100. But, I still don't understand why there is a difference in the use of a ```view``` function between Solang and Remix. Also, how does changing the value of endowment affect the deployment of code.

**Comment by seanyoung** [comment]
solc is of the opinion that events can only be emitted in non-view functions. For example

```
contract c {
	event X(bool);

	function test() view public {
		emit X(true);
	}
}
```
solc will refuse to compile this. However, on Substrate, events can be emitted on RPC calls.

Actually events are currently being implemented in polkadot ui. Having events in rpc calls is very nice, so let's keep this issue open until the UI has implemented this.

**Comment by seanyoung** [comment]
So it turns out that `emit` in view/pure functions does nothing in Substrate. So, I've changed solang to match solc

Should be fixed now.

**Comment by JeremyConnor** [comment]
@seanyoung  I just updated my Solang and it refuses to compile. I get an error in one of the libraries. The error as seen in the terminal output is : 
```
error: could not find native static library `lldELF`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `solang`.
```

**Comment by seanyoung** [comment]
@JeremyConnor there have been some changes which require some updates to the llvm libraries.

You can get the right llvm build here: https://solang.readthedocs.io/en/latest/installing.html#installing-the-llvm-libraries

**Comment by JeremyConnor** [comment]
@seanyoung I followed the link that you provided, but I am still getting the same error.

**Comment by seanyoung** [comment]
That's odd. What platform are you on (and what linux distribution of its linux?)

What's the output of `llvm-config --version` and  `llvm-config --libdir`? 

`llvm-config --libdir` prints a directory, what files do you have in that directory?

Thanks

**Comment by JeremyConnor** [comment]
@seanyoung I am using Ubuntu 20.04 and the output of the other 2 commands are :
![Screenshot from 2020-11-16 07-48-29](https://user-images.githubusercontent.com/73089748/99206028-56f53480-27e0-11eb-8e3d-729dfac109f2.png)

**Comment by seanyoung** [comment]
I'm not sure what is going on here, everything seems in place. Please can you try `git clean -fdx` to clean the  solang directory (please make sure you have copies of files you want in the solang directory), and then do `cargo build` again.

If it still fails, could you please give the output of `cat target/debug/build/solang-*/output`

Thanks for your patience with this.

**Comment by JeremyConnor** [comment]
@seanyoung  I tried it but the error still persists.
Below is the output of ```cat target/debug/build/solang-*/output```
![Screenshot from 2020-11-16 17-19-38](https://user-images.githubusercontent.com/73089748/99249420-1a512980-2830-11eb-93e2-4c11be17f105.png)

**Comment by seanyoung** [comment]
So strange, the file liblldELF.a is present, it has the right path, but still refuses to link it. 

Would you mind checking the file is ok:
```
$ md5sum llvm10.0-linux.tar.gz llvm10.0/lib/liblldELF.a 
2030617f2ed00db7506092ff6da9d3a7  llvm10.0-linux.tar.gz
1d8ddfb8a0e7de04a467275fce1d8ba6  llvm10.0/lib/liblldELF.a
```
and that it has the right permissions:
```
$ ls -l llvm10.0/lib/liblldELF.a
-rw-r--r--. 1 sean sean 9918108 Nov  9 10:48 llvm10.0/lib/liblldELF.a
```
thanks

**Comment by JeremyConnor** [comment]
@seanyoung  I checked it, and it looks perfectly fine. I got the same expected output

**Comment by seanyoung** [comment]
Weird! I'll install ubuntu 20.04 in a vm and see if I can reproduce the issue. What version of rust are you using? Installed via rustup or apt-get install ?
Thanks

**Comment by JeremyConnor** [comment]
I am using 1.47.0 version of rust. I installed it using rustup

**Comment by seanyoung** [comment]
I'm having a hard time reproducing this issue. Would you mind telling me what llvm/lld packages you have installed? 
```
$ dpkg -l llvm* lld*
```
Thanks

**Comment by JeremyConnor** [comment]
Here is the output of the above mentioned command:
![Screenshot from 2020-11-16 19-45-41](https://user-images.githubusercontent.com/73089748/99262809-67d79180-2844-11eb-8554-027ff2368362.png)

**Comment by seanyoung** [comment]
I can't reproduce the issue of solang not building. Not sure what is going on.

@JeremyConnor is the original issue now resolved?

**Comment by JeremyConnor** [comment]
I changed the Smart Contract code, and therefore, no longer required ```view```. So, I didn't encounter this error again. I don't know if the issue would persist if I used a view function again.

**Comment by seanyoung** [comment]
ok well it should be fixed by https://github.com/hyperledger-labs/solang/commit/54847f75eede6d0009bd7676a28262d9a7a8d096
